# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UnsplashAPIDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UnsplashAPI
  pod 'AFNetworking', '~> 3.0'
  pod 'YYModel'
  pod 'SDWebImage/WebP'
end
